### ISSUE TITLE
python-smtp-mail-sending-tester using --usessl

### ISSUE THREAD

**Issue by muhammadfaisal678** [turbodog/python-smtp-mail-sending-tester#2]
connect: ('192.168.1.119', 25)
connect: ('192.168.1.119', 25)
Traceback (most recent call last):
  File "smtptest.py", line 84, in <module>
    server.connect(serveraddr, options.serverport)
  File "C:\Python27\lib\smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Python27\lib\smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "C:\Python27\lib\ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)

**Comment by tenbob** [comment]
Sorry for late reply, but it may help others. The error message is [SSL: UNKNOWN_PROTOCOL]. This means the server you connected to doesn't understand the protocol you are sending. So check out the remote server or experiment to find out what protocol it does support.  

It looks like you are trying to connect on port 25. This is not usually configured for `--usessl`. So that's probably the reason it is not working.

Typical server configurations are 
* port 25. unencrypted or `--usetls` (which is really STARTTLS).
* port 465. `--usessl`.
* port 587. `--usetls` (which is really STARTTLS).

This is probably not a bug in this repo.
